export const BLOG_TAGS = [
    'data analytics',
    'dashboard development',
    'conversion rate optimization',
    'ad operations',
    'user experience',
    'frontend development',
    'search engine optimization',
    'ai search optimization',
    'content marketing',
    'organic social media',
    'email marketing',
    'app store optimization',
    'digital pr',
    'influencer marketing',
    'paid search',
    'paid social',
    'programmatic advertising',
    'display advertising',
    'streaming advertising',
    'marketplaces advertising',
    'media strategy & planning',
    'website design',
    'branding',
    'graphic & motion design',
    'performance creative',
    'content production',
    'audio production',
    'wordpress development',
    'plugin integration',
    'website maintenance',
    'e-commerce solutions',
    // Additional related tags:
    'digital marketing tools',
    'growth hacking',
    'marketing automation',
    'seo tools',
    'content strategy',
    'social media tools',
    'ppc campaign',
    'analytics insights'
  ];
  